
import Navbar2 from "./components/Navbar/Navbar2";
import Hero from "./components/columns/hero";
import Hero2 from "./components/columns/hero2";
import NewArrivals from "./components/columns/NewArrivals";
import BestSeller from "./components/columns/BestSeller";
import TopBiography from "./components/columns/TopBiography";
import Footer from "./components/Footer/Footer";
import ExploreGenre from "./components/columns/ExploreGenre";
export default function Home() {
  return (
    <>
      

      <Hero2 />
      <ExploreGenre/>
      <NewArrivals/>
      <TopBiography/>
      <BestSeller/>
      
      
     
    </>
  );
}


export const metadata = {
  title: "Bokenplek",
  description: "Generated by create next app",
};