import Navbar from "./components/Navbar/Navbar";
import Navbar2 from "./components/Navbar/Navbar2";
import Hero from "./components/columns/hero";
import Hero2 from "./components/columns/hero2";
import NewArrivals from "./components/columns/NewArrivals";
import SimilarBooks from "./components/SimilarBooks";
export default function Home() {
  return (
    <>
      <Navbar2 />
      
      <Hero2 />
      <NewArrivals/>

      
      
      <div className="h-[1000px] bg-black"></div>

    </>
  );
}


export const metadata = {
  title: "Bokenplek",
  description: "Generated by create next app",
};